name: DCarbon Dev CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    outputs:
      image: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test

      - name: Set Docker Image Tag
        id: set-image-tag
        run: echo "image=${{ secrets.AZURE_ACR_LOGIN_SERVER }}/dcarbonweb:latest" >> $GITHUB_OUTPUT

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Azure with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_GITHUB_ACCESS }}

      - name: Log in to Azure Container Registry
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/dcarbonweb:latest .

      - name: Push to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/dcarbonweb:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ${{ secrets.AZURE_ACR_LOGIN_SERVER }} \
              --username ${{ secrets.AZURE_ACR_USERNAME }} \
              --password ${{ secrets.AZURE_ACR_PASSWORD }}

            docker pull ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/dcarbonweb:latest

            docker stop dcarbonweb || true && docker rm dcarbonweb || true

            docker run -d --name dcarbonweb \
              -e NEXT_PUBLIC_API_URL=https://services.dcarbon.solutions \
              -p 3100:3000 \
              ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/dcarbonweb:latest
